### ISSUE TITLE
Unable to draw rectangle

### ISSUE THREAD

**Issue by bcorwen** [blazer82/FT81x_Arduino_Driver#11]
Hello blazer82,

I've built my own FT81x driver board, following your excellent design, and have got the display up and running with some of the examples from your library.

However, in starting to draw my own screens, I find that the rectangles are not displaying at all.

For example:
`ft81x.drawCircle(20,20,4,FT81x_COLOR_RGB(255, 0, 0));` will draw successfully, but
`ft81x.drawRect(20,20,4,4,0,FT81x_COLOR_RGB(255, 0, 0));` will not display anything.

Is there a known error in the rectangle drawing routine? It appears to correctly follow the FT81x programming guide. Could this be a fault with the driver chip or hardware fault?

bcorwen

**Comment by blazer82** [comment]
Hey @bcorwen, very cool that you built your own! 😃 

I'm sorry to hear that you ran into issues, though. To me there's no known problem with drawing rectangles. I'm not sure what's happening here. If you just replace the `drawCircle` call with that `drawRect` call I'd expect it to work properly. 

I also think it's pretty unlikely that it's an issue with the chip or the hardware in general since other examples seem to work just fine... 🤔

**Comment by bcorwen** [comment]
I've found the problem after a little trial and error. Sharing in case it helps others.

In my example, I was using the following parameters:
`ft81x.drawRect(20,20,4,4,0,FT81x_COLOR_RGB(255, 0, 0));`
I assumed corner size should be 0 for a perfect rectangle with sharp corners.

However I should be using a value of 1, as this draws rectangles successfully without any soft corners.

Simple mistake to make. I'm just glad it's all working!

Thanks again for your library and board design!

**Comment by bcorwen** [comment]
I've found the problem after a little trial and error. Sharing in case it helps others.

In my example, I was using the following parameters:
`ft81x.drawRect(20,20,4,4,0,FT81x_COLOR_RGB(255, 0, 0));`
I assumed corner size should be 0 for a perfect rectangle with sharp corners.

However I should be using a value of 1, as this draws rectangles successfully without any soft corners.

Simple mistake to make. I'm just glad it's all working!

Thanks again for your library and board design!

**Comment by blazer82** [comment]
@bcorwen very happy that you've figured it out, and thanks for sharing the solution!
