### ISSUE TITLE
Wrong constant define: FT81x_BITMAP_LAYOUT_ARGB1555 should be 0x00, not 0x01.

### ISSUE THREAD

**Issue by dinoghi** [blazer82/FT81x_Arduino_Driver#14]
Line 156 of  FT81x_Arduino_Driver/src /FT81x.h is:
```
#define FT81x_BITMAP_LAYOUT_ARGB1555 0x1  ///< Bitmap pixel format ARGB1555
```
but it should be (from FT81x programming manual):

```
#define FT81x_BITMAP_LAYOUT_ARGB1555 0x0 
```

With this definition is possible to copy-paste-modify the drawBitmap function and obtain a routine with the 1-bit alpha display (quick and dirty way, but works), changing the bitmap layout command  replacing FT81x_BITMAP_LAYOUT_RGB565 with FT81x_BITMAP_LAYOUT_ARGB1555:
like this: 

```
 intermediateCmd(BITMAP_LAYOUT(FT81x_BITMAP_LAYOUT_ARGB1555, (uint32_t)width * 2, (uint32_t)height));  // only supporting one format for now
```
    
Best regards, 
Dino.

**Comment by blazer82** [comment]
Thanks a lot! I checked and you're right!
It's been fixed in version 0.14.0
