### ISSUE TITLE
Image.ino

### ISSUE THREAD

**Issue by sergpenshin** [blazer82/FT81x_Arduino_Driver#7]
Hello Raphael.
Would you please tell me how did you get array of image data in **const uint8_t jpegData[] PROGMEM = {...};**
Is there any program for convert jpeg/png images to array?

Best regards,
Sergey

**Comment by blazer82** [comment]
Hi Sergey,

When using JPEG I think you have to use the JFIF format. Then just take the raw bytes from the file and convert them to HEX.

Also, it's probably best to use the [EVE Asset Builder](https://brtchip.com/eve-toolchains/#EVEAssetBuilder) provided by the manufacturer of the chip on the board to convert image files.

Let me know if any of this works for you.

**Comment by sergpenshin** [comment]
Hi,
Definitely, RAW data of images should be inserted to the **const uint8_t jpegData[]**
The code works great with JPG pictures, but only with sizes of images up to 255x255. I don't now why.
I think it might has something to do with the drawBitmap, because i tried using **ft81x.drawBitmap**, without **ft81x.loadImage(0, JPEG_SIZE, jpegData);** , but it works correctly only until 255x255 size too.

For convert JPG images i used [https://lvgl.io/tools/imageconverter](url)

**Comment by blazer82** [comment]
The graphics memory on the chip is limited to 1 mb. If the image is too big it won't work because of that.

Great to hear that you found a way to make it work. PNG should work, too.
